todo/task/urls.py
from django.urls import path
from . import views


app_name = 'task'
urlpatterns = [
	path('update/<int:pk>/', views.update_task, name='update'),
	path('', views.index, name='index'),
	path('delete/<int:pk>/', views.delete_task, name='delete'),
]

todo/todo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
	path('', include('task.urls')),
    path('admin/', admin.site.urls),
]

todo/task/models.py
from django.db import models

# Create your models here.
class Task(models.Model):
	title = models.CharField(max_length=200)
	complete = models.BooleanField(default=False)
	created = models.DateTimeField(auto_now_add=True)


	def __str__(self):
		return self.title

todo/task/forms.py
from django import forms
from .models import Task


class TaskForm(forms.ModelForm):
	class Meta:
		model = Task
		fields = '__all__'

todo/task/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from .models import Task
# Create your views here.
from .forms import TaskForm

def index(request):
	tasks = Task.objects.all().order_by('-created')
	form = TaskForm()
	if request.method == "POST":
		form = TaskForm(request.POST)
		if form.is_valid():
			form.save()
		return redirect('task:index')
	context = {
		'form': form,
		'tasks': tasks
	}
	return render(request, 'task/list.html', context)
	#return HttpResponse("Index")

def update_task(request, pk):
	instance = Task.objects.get(pk=pk)
	 
	if request.method == "POST":
		print("I ran")
		form = TaskForm(request.POST, instance=instance)
		if form.is_valid():
			form.save()
		return redirect('task:index')
	form = TaskForm(instance=instance)
	context = {
		'form': form
	}
	return render(request, 'task/update_task.html', context)

def delete_task(request, pk):
	task_object = get_object_or_404(Task, id=pk)
	if request.method == "POST":
		task_object.delete()
		return redirect('task:index')
	context	= {
		'task': task_object
	}
	return render(request, 'task/confirm_delete.html', context)

todo/task/templates/task/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
	<!-- load our static css -->
    <link rel="stylesheet" href="{% static 'css/task.css' %}">

	<title>ToDo App {% block title %}{% endblock %}</title>
</head>
<body>
	<div class="container">
		<div class="row">
			<div class="col-md-8 m-auto">
				{% block content %}{% endblock %}
			</div>
		</div>
	</div>
</body>
</html>

todo/task/templates/task/confirm_delete.html
{% extends 'task/base.html' %}
{% block content %}
<div class="task-card">
	<p>Are you sure you want to delete "{{ task }}"?</p>
	<form method="post" action="">
		{% csrf_token %}
		<input class='btn btn-sm btn-info' type="submit" name="" value="delete">
		<a class='btn btn-sm btn-info' href="{% url 'task:index' %}">Cancel</a>
	</form>

	

</div>
{% endblock content %}

todo/task/templates/task/list.html
{% extends 'task/base.html' %}
{% block content %}
<h3>To do</h3>
<div class='task-card'>
	<div class="form-group">
		<form method='post' action="{% url 'task:index' %}">
			{% csrf_token %}
			{{ form.title }}
			<input class="btn btn-success btn-sm"  type="submit" name="" value="create task">
		</form>
	</div>
	<div class="task-list">
		{% for task in tasks %}
		<ul class="card">
			<li class="card-body">
				{% if task.complete == True %}
					<strike>{{task.title}}</strike>
				{% else %}
					{{ task.title }}
				{% endif %}
				<div class="but">
					<a class='btn btn-sm btn-info' href="{% url 'task:update' task.id %}"> edit</a>
					<a class='btn btn-sm btn-danger' href="{% url 'task:delete' task.id %}">delete</a>
				</div>
			</li>
		</ul>
		{% endfor %}
	</div>
</div>
{% endblock content %}

todo/task/templates/task/update_task.html
{% extends 'task/base.html' %}
{% block content %}
<h3>Update Task</h3>
<div class="task-card">
	<form method="POST">
		{% csrf_token %}
		{{form.as_p}}
		<input type="submit" name="" value="update">
		
	</form>
</div>
{% endblock content %}